const ContactActionTypes = {
    FETCH_CONTACTS_START: 'FETCH_CONTACTS_START',
    FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
    FETCH_CONTACTS_FAILURE: 'FETCH_CONTACTS_FAILURE',
    FILTER_CONTACTS: 'FILTER_CONTACTS',
    REMOVE_CONTACT: 'REMOVE_CONTACT',
    ADD_CONTACTS_REQUEST: 'ADD_CONTACTS_REQUEST',
    ADD_CONTACT: 'ADD_CONTACT',
  };
  
  export default ContactActionTypes;
  